.vscode/settings.json, lib/data/cyberjapandata.gsi.go.jp/xyz/english/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/pale/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/relief/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/seamlessphoto/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/std/index.yaml
Reference:
- https://maps.gsi.go.jp/development/ichiran.html
Added following data definitions:
- lib/data/cyberjapandata.gsi.go.jp/xyz/english/index.yaml
- lib/data/cyberjapandata.gsi.go.jp/xyz/pale/index.yaml
- lib/data/cyberjapandata.gsi.go.jp/xyz/relief/index.yaml
- lib/data/cyberjapandata.gsi.go.jp/xyz/seamlessphoto/index.yaml
- lib/data/cyberjapandata.gsi.go.jp/xyz/std/index.yaml
=> Add GIS tile maps

lib/data/README.md
Adds a README.md file to the `lib/data` directory to describe the YAML file fields and provide usage examples.
- **Creates a README.md file** in the `lib/data` directory, fulfilling the task requirement.
- **Describes the purpose** of the `lib/data` directory and the significance of the YAML files contained within.
- **Explains each YAML file field** including `data_id`, `license`, `attributions`, `description`, `file_format`, `file_size`, `url`, `max_zoom`, and `min_zoom`, providing clarity on their usage.
- **Provides examples** for each field to aid users in understanding how to utilize the information in the YAML files effectively.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/yuiseki/foil4g?shareId=93466146-9f0b-4601-b96c-740468dd4 …
=> Add README.md to lib/data directory

lib/data/README.md
Updates the `lib/data/README.md` to enhance clarity and compliance with project requirements.
- **Revises field descriptions:** Separates the fields into 'Required Fields' and 'Optional Fields' sections to clearly distinguish between mandatory and optional fields in the YAML files.
- **Removes examples section:** Deletes the examples section to focus the document on field specifications, aligning with the task's requirement to exclude examples.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g?shareId=1674365a-5f5a-45bd-b0fb-8beb7d4ed085).
=> Refine README to distinguish between mandatory and optional YAML fields

UNopenGIS/foil4g/.github/ISSUE_TEMPLATE/bug_report.md, UNopenGIS/foil4g/.github/ISSUE_TEMPLATE/data_addition.md
This pull request introduces two new GitHub Issue templates for the UNopenGIS/foil4g repository to streamline the process of reporting bugs and suggesting data additions.
- **Adds a bug report template**: This template guides users through reporting a bug by including sections for describing the issue, steps to reproduce, expected behavior, and actual behavior. It also includes metadata such as a default label for bug reports.
- **Adds a data addition template**: This template is designed for users to suggest new data sources for inclusion in the project. It prompts for details such as the data source description, format, license, and URL, along with a section for additional context.
These templates aim to improve the quality of issues submitted by providing structured formats for …
=> Add GitHub Issue templates for bug report and data addition

lib/data/tile.openstreetmap.fr/hot/index.yaml
Related to #7
Adds the OpenStreetMap HOT style by OSM France as a new data source in the repository.
- **Data Source Addition**: A new YAML file `lib/data/tile.openstreetmap.fr/hot/index.yaml` has been created to include the OpenStreetMap HOT style by OSM France as a data source.
- **Content Details**: The file specifies the `data_id`, `license` (ODbL), `attributions` to OpenStreetMap contributors, `description` of the map style, `file_format` (png), `file_size` (unknown), `url` pattern for accessing the tiles, and `max_zoom` and `min_zoom` levels.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/7?shareId=778bd0a9-9c05-4633-b6d3-f69a6771437a).
=> Add OpenStreetMap HOT style by OSM France as a data source

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.ja.md, README.md
Adds a new `CODE_OF_CONDUCT.md` file and updates documentation to reference it, enhancing the project's community guidelines and contribution process.
- **Adds `CODE_OF_CONDUCT.md`**: Introduces a new file adapted from the Contributor Covenant, version 2.1, establishing clear community standards and enforcement guidelines.
- **Updates `CONTRIBUTING.md`**: Modifies the Code of Conduct section to include a direct link to the new `CODE_OF_CONDUCT.md`, ensuring contributors are aware of the conduct guidelines.
- **Revises `README.md` and `README.ja.md`**: Both files are updated to reference the new Code of Conduct, making it accessible to both English and Japanese speaking contributors.
---
For more details, open the [Copilot Workspace …
=> Add Code of Conduct to the repository

lib/data/server.arcgisonline.com/world_imagery/index.yaml
- Close: #15
Adds the ArcGIS World Imagery data source to the repository.
- **Data Source Configuration**: Creates a new YAML file `lib/data/server.arcgisonline.com/world_imagery/index.yaml` with configuration for the ArcGIS World Imagery. This includes setting the `data_id` as `arcgis_world_imagery`, specifying the `license` as unknown, and defining the `file_format` as png.
- **Attributions and URL**: Adds attributions to Esri, Maxar, Earthstar Geographics with a link to the ArcGIS service. Provides the URL for accessing the World Imagery tiles.
- **Metadata**: Sets the `description` for the data source, indicating it is a raster tile map of World Imagery by ArcGIS, Esri. Also, specifies the `max_zoom` level as 22 and `min_zoom` as 0, with `file_size` marked as unknown.
---
For more …
=> Add ArcGIS World Imagery data source

lib/data/www.naturalearthdata.com/ne_10m_coastline/index.yaml
- Close: #18
Adds a new YAML file to the repository to include the Natural Earth coastline data at a 1:10m scale.
- Adds `lib/data/www.naturalearthdata.com/ne_10m_coastline/index.yaml` defining the data source with attributes such as `data_id`, `license`, `attributions`, `description`, `file_format`, `file_size`, and `url`.
- Specifies the data as a zipped shapefile of the coastline at a 1:10m scale from Natural Earth, under public domain license, with attributions to Natural Earth and their website.
- Lists the file size as 2.9MB and provides a direct download URL for the zipped shapefile.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/18?shareId=82a70989-ec46-4c23-ba8d-58730998807a).
=> Add Natural Earth coastline 1:10m data source

lib/data/www.geospatial.jp/hinanbasho/index.yaml
- Close: #20
Adds a description to the `lib/data/www.geospatial.jp/hinanbasho/index.yaml` file.
- Adds the specified description "国土地理院の提供している全国指定避難場所をShapefile化したデータ" to the YAML file to address the issue of missing description content.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/20?shareId=a4c77aad-c7ec-4fc2-8412-c95856420c87).
=> Add description to geospatial_jp_hinanbasho data

lib/api/nominatim.openstreetmap.org/reverse/index.yaml, lib/api/nominatim.openstreetmap.org/search/index.yaml
- Close: #25
Adds the Nominatim API to the repository with the API definition split into two YAML files as specified in the issue.
- **Search API Definition**: Adds `lib/api/nominatim.openstreetmap.org/search/index.yaml` with fields for `api_id`, `description`, `endpoint_url`, and `parameters` including `format` and `q` to define the search functionality of the Nominatim API.
- **Reverse API Definition**: Adds `lib/api/nominatim.openstreetmap.org/reverse/index.yaml` with fields for `api_id`, `description`, `endpoint_url`, and `parameters` including `format`, `lat`, `lon`, and `zoom` to define the reverse geocoding functionality of the Nominatim API.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/25?shareId=012bdaa …
=> Add Nominatim API definitions

lib/api/README.md
- Close: #29
Adds a README.md file to the `lib/api` directory, providing guidelines for API YAML files.
- **Creates a README.md file** in the `lib/api` directory, outlining the purpose of the directory and the structure of the API YAML files it contains.
- **Details required and optional fields** for the API YAML files, including `api_id`, `description`, `endpoint_url`, `parameters`, and `license`, with explanations for each.
- **Encourages contributions** by providing instructions on how to add new API YAML files to the directory, and linking to the project's CONTRIBUTING.md file for more detailed contribution guidelines.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/29?shareId=078199bb-0fac-4a2c-8585-4f322d6071 …
=> Add README.md to lib/api directory

.vscode/settings.json, lib/data/README.md, lib/data/cyberjapandata.gsi.go.jp/xyz/english/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/pale/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/relief/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/seamlessphoto/index.yaml, lib/data/cyberjapandata.gsi.go.jp/xyz/std/index.yaml, lib/data/data.source.coop/smartmaps/toshik/index.yaml, lib/data/download.geofabrik.de/asia/japan/index.yaml, lib/data/download.geofabrik.de/asia/japan/kanto/index.yaml, lib/data/download.geofabrik.de/europe/monaco/index.yaml, lib/data/server.arcgisonline.com/world_imagery/index.yaml, lib/data/tile.openstreetmap.fr/hot/index.yaml, lib/data/tile.openstreetmap.jp/osm-bright/index.yaml, lib/data/tile.openstreetmap.jp/planet/index.yaml, lib/data/tile.openstreetmap.jp/planet_pmtiles/index.yaml, lib/data/tile.openstreetmap.org/index.yaml, lib/data/ucdp.uu.se/ged231-csv.zip/index.yaml, lib/data/www.geospatial.jp/hinanbasho/index.yaml, lib/data/www.naturalearthdata.com/ne_10m_coastline/index.yaml
- Add `data_format` field for YAML files in `lib/data/`
- `file_format` は、そのフィールド名のとおり、データのファイルフォーマットのみを正確に表現するべきである
- そうすると、 `file_format` だけではデータの具体的なフォーマットの説明として不十分である
- `data_format` フィールドを追加する
=> Add `data_format` field for YAML files in `lib/data/`

lib/data/tile.openstreetmap.fr/hot/index.yaml, public/stylejson/cyberjapandata.gsi.go.jp/xyz/relief/style.json, public/stylejson/server.arcgisonline.com/world_imagery/style.json, public/stylejson/tile.openstreetmap.fr/hot/style.json, public/stylejson/tile.openstreetmap.org/style.json
- SSIA
- We need style.json for each `xyz_raster_tiles` data to show map with maplible-gl-js
- Add `public/stylejson` dir
- Add several `style.json` files
=> Add `public/stylejson` dir and `style.json` files

.github/ISSUE_TEMPLATE/add_new_api.md, .github/ISSUE_TEMPLATE/add_new_data.md, .github/ISSUE_TEMPLATE/add_new_task.md
=> Tweak issue templates, Add `add_new_task` template

lib/data/optgeo.github.io/virgo-data/20200122_vcc_landuse_final_2015.yaml
- Close: #45
Adds metadata for the Vientiane, Lao P. D. R., land use data for the year 2015 to the repository.
- Introduces a new YAML file `lib/data/optgeo.github.io/virgo-data/20200122_vcc_landuse_final_2015.yaml` containing detailed metadata about the land use data.
- Specifies `data_id` as `optgeo_vcc_landuse_final_2015`.
- Sets the `license` field to `unknown`.
- Includes `attributions` to the Vientiane Integrated Urban Information GIS-based Opendata Platform with a URL link.
- Describes the data as land use information for Vientiane for the year 2015.
- Defines `data_format` as `shapefile` and `file_format` as `shp`.
- Marks `file_size` as `unknown`.
- Provides the source URL for the data.
---
For more details, open the [Copilot Workspace …
=> Add Vientiane land use data

lib/data/optgeo.github.io/virgo-data/22kv_underground_line_future_plan_v1.yaml
- Close: #46
Adds a new YAML file for the `22kv_underground_line_future_plan_v1.shp` data to the repository.
- **File Addition**: Creates `lib/data/optgeo.github.io/virgo-data/22kv_underground_line_future_plan_v1.yaml` to include metadata for the shapefile data.
- **Metadata Details**: Specifies `data_id`, `license`, `attributions`, `description`, `data_format`, `file_format`, `file_size`, and `url` as per the issue description, ensuring proper documentation and accessibility of the data.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/46?shareId=48c94938-842b-439d-94af-d0cd68401dc3).
=> Add 22kv underground line future plan data

lib/data/optgeo.github.io/virgo-data/determiningroad_v0.yaml
- Close: #48
Adds a new YAML file to the repository to include metadata for the determining road data for Vientiane, Lao P. D. R.
- **Metadata Addition**: Introduces `lib/data/optgeo.github.io/virgo-data/determiningroad_v0.yaml` containing essential metadata such as data ID, license status (unknown), attributions to Vientiane Integrated Urban Information GIS-based Opendata Platform, description of the data, data format (shapefile), file format (shp), file size (unknown), and the URL for data access.
- **Attribution Details**: Specifies dual attributions, including a link to the disclaimer page of the Vientiane Integrated Urban Information GIS-based Opendata Platform, acknowledging the source of the data.
---
For more details, open the [Copilot Workspace …
=> Add determining road data for Vientiane

lib/data/optgeo.github.io/virgo-data/electric_pole_point_v1.yaml
- Close: #51
Adds a new YAML file for electric pole data in Vientiane, Lao P. D. R. to the repository.
- Introduces `lib/data/optgeo.github.io/virgo-data/electric_pole_point_v1.yaml` with comprehensive details about the electric pole data.
- Specifies fields such as `data_id`, `license`, `attributions`, `description`, `data_format`, `file_format`, `file_size`, and `url`, aligning with the structure of existing data files in the repository.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/51?shareId=64b3570f-fbe7-4099-8a76-b53d496f068e).
=> Add electric pole data for Vientiane

lib/data/optgeo.github.io/virgo-data/electric_22kv_vtc_line_v1.yaml
- Close: #49
Adds a new YAML file to include the electric 22kV VTC line data for Vientiane, Lao P. D. R. in the repository.
- **File Addition**: Creates `lib/data/optgeo.github.io/virgo-data/electric_22kv_vtc_line_v1.yaml` to store metadata about the electric 22kV VTC line data.
- **Metadata Fields**: Specifies `data_id`, `license`, `attributions`, `description`, `data_format`, `file_format`, `file_size`, and `url` within the new YAML file.
- **Content Details**: Sets the `license` as unknown, lists the Vientiane Integrated Urban Information GIS-based Opendata Platform under `attributions`, and provides a URL to the Shapefile data.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/49?shareId=c8e59912-691b-4441-b719-0 …
=> Add electric 22kV VTC line data for Vientiane

lib/data/optgeo.github.io/virgo-data/firehydrant_2023_v1.yaml
- Close: #53
Adds a new YAML file `firehydrant_2023_v1.yaml` to the `lib/data/optgeo.github.io/virgo-data/` directory to include metadata about the fire hydrant data for Vientiane, Lao P. D. R., for the year 2023.
- **Metadata Details**: Specifies the data ID, license as unknown, attributions to the Vientiane Integrated Urban Information GIS-based Opendata Platform, and a description of the data.
- **Data Format**: Indicates the data format as shapefile, with the file format specified as `.shp`.
- **Data Source**: Includes the URL to the shapefile data.
- **Additional Information**: Lists file size as unknown.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/53?shareId=34ada644-9922-44ee-a33d-c94b92796b12).
=> Add fire hydrant data for Vientiane

lib/data/optgeo.github.io/virgo-data/goverment_office_v0.yaml
- Close: #55
Adds a new YAML file to include government office data for Vientiane, Lao P. D. R. in the repository.
- Introduces `lib/data/optgeo.github.io/virgo-data/goverment_office_v0.yaml` with comprehensive details including a unique data identifier, license status, attributions to the Vientiane Integrated Urban Information GIS-based Opendata Platform, and a description of the data.
- Specifies the data format as shapefile and file format as shp, with the file size marked as unknown.
- Provides a URL to access the government office data directly.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/55?shareId=48a73ea3-facd-4ffa-90a2-cb60495b7603).
=> Add government office data for Vientiane

lib/data/optgeo.github.io/virgo-data/provinceboundary_cdudcp_v1.yaml
- Close: #57
Adds a new YAML file for the province boundary data of Vientiane, Lao P. D. R. to the repository.
- **File Addition**: Introduces `provinceboundary_cdudcp_v1.yaml` under `lib/data/optgeo.github.io/virgo-data/`, containing essential metadata about the province boundary data.
- **Metadata Details**: Includes fields such as `data_id`, `license`, `attributions`, `description`, `data_format`, `file_format`, `file_size`, and `url`, with the `license` specified as "unknown" and a note about the data's open data intention.
- **Attributions**: Credits the Vientiane Integrated Urban Information GIS-based Opendata Platform with a link to their disclaimer page.
- **Data Accessibility**: Provides a URL pointing to the Shapefile's location, facilitating access to the province boundary …
=> Add province boundary data for Vientiane

lib/data/optgeo.github.io/virgo-data/transmission_line_v1.yaml
- Close: #63
Adds a new YAML file for the transmission line data in Vientiane, Lao P. D. R. to the `lib/data/optgeo.github.io/virgo-data` directory.
- **File Creation**: Creates `transmission_line_v1.yaml` with detailed metadata about the transmission line data.
- **Metadata Fields**: Includes fields for `data_id`, `license`, `attributions`, `description`, `data_format`, `file_format`, `file_size`, and `url`, providing comprehensive information about the data source, format, and access.
- **Data Source and Format**: Specifies the data format as "shapefile" and the file format as "shp", with a direct URL to access the shapefile data.
- **License and Attribution**: Marks the license as "unknown" but notes the data's intention to be open, attributing it to the Vientiane Integrated Urban …
=> Add transmission line data for Vientiane

.vscode/settings.json, package-lock.json, package.json, public/stylejson/opencellid.org/style.json, src/components/BaseData/OpenCellId/index.stories.ts, src/components/BaseData/OpenCellId/index.tsx, src/components/BaseMaps/OpenStreetMap/OpenStreetMapFrHotRaster/index.tsx, src/components/BaseMaps/OpenStreetMap/OpenStreetMapJpOSMBrightVector/index.tsx, src/components/BaseMaps/OpenStreetMap/OpenStreetMapOrgRaster/index.tsx, src/components/BaseMaps/SatelliteImagery/ArcGISWorldImagery/index.tsx, src/components/BaseMaps/SatelliteImagery/GSISeamlessPhoto/index.tsx, src/components/BaseMaps/UNClearMapRaster/index.tsx
=> Add OpenCellId for example of preview of BaseData

.vscode/settings.json, lib/data/data.source.coop/smartmaps/dem1a/index.yaml, src/components/Datasets/DEM1A/index.stories.ts, src/components/Datasets/DEM1A/index.tsx, src/components/Datasets/DEM1A/source.ts
=> Add preview of DEM1A by Smart Maps Group

src/components/Datasets/GoogleOpenBuildings/index.tsx
This is to change the initial map extent of GoogleOpenBuildingsMap.
- This will change the initiali center and zoom of the map.
- To demonstrate the value of using Google Open Buildings. 
- By changing `center` and `zoom` of `map`.
=> Update index.tsx - change map center

src/components/Datasets/ArmedConflict/index.stories.ts, src/components/Datasets/DEM1A/index.stories.ts, src/components/Datasets/GEL/index.stories.ts, src/components/Datasets/OpenCellId/index.stories.ts, src/components/Datasets/OvertureMaps/index.stories.ts, src/components/Datasets/Rwanda10/index.stories.ts, src/components/Datasets/VientianeLanduse/index.stories.ts, src/components/Maps/OpenStreetMap/OpenStreetMapFrHotRaster/index.stories.ts, src/components/Maps/OpenStreetMap/OpenStreetMapJpOSMBrightVector/index.stories.ts, src/components/Maps/OpenStreetMap/OpenStreetMapOrgRaster/index.stories.ts, src/components/Maps/SatelliteImagery/ArcGISWorldImagery/index.stories.ts, src/components/Maps/SatelliteImagery/GSISeamlessPhoto/index.stories.ts, src/components/Maps/UNClearMapRaster/index.stories.ts
- 名前付きimportを `as MapComponent` とすることでコードを共通化する
- GitHub Copilot Workspaceがコードを理解しやすくするため
=> refactor: import map as `MapComponent`

src/examples/Visualization/Heatmap/ArmedConflict/index.stories.tsx, src/examples/Visualization/Heatmap/ArmedConflict/index.tsx, src/examples/Visualization/Heatmap/ArmedConflict/source.ts
=> Add visualization example: heatmap

.github/workflows/ollama.yml
This pull request updates the `.github/workflows/ollama.yml` file to streamline the setup and execution of the Ollama Docker image. The most important changes include replacing the manual installation and setup steps with Docker commands.
Key changes:
* Replaced the manual creation of the Ollama models directory and the caching of the Ollama directory with a Docker volume mount.
* Removed the steps to install and start Ollama manually, replacing them with commands to run the Ollama Docker image and pull the `gemma2:2b` model.
* Updated the command to invoke the `gemma2:2b` model to ask a different question: "Who is the current Secretary General of the United Nations?"
=> Update Ollama workflow to use Docker for model management and invocation

lib/commands/gdal/gdal_translate.ja.md, lib/commands/gdal/gdalinfo.ja.md, lib/commands/gdal/gdalwarp.ja.md, lib/commands/gdal/ogr2ogr.ja.md, lib/commands/gdal/ogrinfo.ja.md
This pull request adds comprehensive Japanese documentation for several GDAL and OGR command-line utilities. Each file provides detailed usage examples, options, and explanations for various functionalities. These changes enhance the accessibility of these tools for Japanese-speaking users.
* [`lib/commands/gdal/gdal_translate.ja.md`](diffhunk://#diff-3a43d9e5bb2e815a0845e5953c7f4e59e263204a056096a4278c0732c3f08df6R1-R44): Added documentation for `gdal_translate`, covering format conversion, resizing, data type changes, and other operations.
* [`lib/commands/gdal/gdalinfo.ja.md`](diffhunk://#diff-d4ff5583dc1f3e885ec56c54885f7ec63e94f1ab020b8659be9f8ec4b7914f1bR1-R35): Added documentation for `gdalinfo`, detailing how to retrieve raster dataset metadata, statistics, and spatial …
=> feat: add lib/commands dir

lib/commands/gdal/ogr2ogr.ja.md, lib/commands/tippecanoe/tippecanoe.ja.md
This pull request adds new documentation examples for two geospatial data processing tools, `ogr2ogr` and `tippecanoe`, in their respective Japanese-language markdown files. The changes include new usage examples and explanations for advanced features.
* Added examples for outputting GeoJSON in sequence format (GeoJSONSeq) and processing newline-delimited features. (`lib/commands/gdal/ogr2ogr.ja.md`, [lib/commands/gdal/ogr2ogr.ja.mdR48-R53](diffhunk://#diff-137d2fffb438bd69a429684d4cd614f622ad35a5c420e3ae5e0f63a63132617fR48-R53))
* Introduced a new section with detailed usage examples for `tippecanoe`, covering tasks like converting GeoJSON to MBTiles, setting zoom levels, filtering attributes, and simplifying geometries. (`lib/commands/tippecanoe/tippecanoe.ja.md`, …
=> Add lib/commands/tippecanoe/tippecanoe.ja.md

lib/commands/osmium/osmium.ja.md
This pull request adds comprehensive documentation in Japanese for the `osmium` command-line tool, which is used to process OpenStreetMap (OSM) data. The documentation includes usage examples, explanations of key functionalities, and descriptions of its subcommands.
* Added an overview of the `osmium` tool, including its purpose and a link to the official website.
* Provided detailed usage examples for common operations, such as file format conversion, data extraction, filtering, merging, exporting, and applying updates.
* Listed and explained the main subcommands of `osmium`, such as `add-locations-to-ways`, `apply-changes`, `tags-filter`, and more, with brief descriptions of their functionality.
=> docs: add Japanese documentation for osmium command

lib/commands/charites/charites.ja.md
This pull request adds a new Japanese documentation file for the `charites` command-line tool, providing a detailed overview of its features and usage. The documentation is aimed at helping users efficiently create and manage vector tile map styles using YAML.
* **Overview of `charites`:** Introduced the tool as a utility for efficiently configuring vector tile map styles in YAML format, adhering to the MapLibre/Mapbox Style Specification. A link to the official documentation is included.
* **Command usage examples:** Added detailed examples for key commands, such as initializing style files, converting between JSON and YAML, building styles, live previewing, and managing layers. Each command is explained with its purpose and syntax.
* **Advanced options:** Documented advanced features …
=> docs: Add charites command documentation in Japanese

lib/commands/gdal/gdal2tiles.py.ja.md, lib/commands/gdal/gdalbuildvrt.ja.md
This pull request adds comprehensive documentation in Japanese for two GDAL utilities, `gdal2tiles.py` and `gdalbuildvrt`. These documents provide detailed usage examples and options for each utility, making it easier for Japanese-speaking users to understand and utilize these tools.
* **`gdal2tiles.py` Documentation**:
- Explains how to convert raster data into web map tiles (XYZ or TMS) compatible with platforms like Google Maps, OpenLayers, and Leaflet.
- Includes examples for generating tiles with specific zoom levels, projections, resampling methods, and more.
* **`gdalbuildvrt` Documentation**:
- Describes how to create virtual raster datasets (VRT) from multiple raster files without duplicating data.
- Provides examples for creating VRTs with specific bands, resolutions, spatial …
=> docs: add Japanese documentation for gdalbuildvrt and gdal2tiles.py
