- .github/ISSUE_TEMPLATE/data_addition.md
> Tweak Data Addition issue template

- .vscode/settings.json
- lib/data/data.source.coop/smartmaps/toshik/index.yaml
> Add 都市計画決定GISデータ PMTiles

- .vscode/settings.json
- lib/data/www.geospatial.jp/hinanbasho/index.yaml
- Add geospatial_jp_hinanbasho data source
- We need more data source
- Add lib/data/www.geospatial.jp/hinanbasho/index.yaml
> Add geospatial_jp_hinanbasho data source

- .github/ISSUE_TEMPLATE/api_addition.md
- Close: #23
Adds a new issue template for API additions to the `.github/ISSUE_TEMPLATE` directory, enhancing the project's ability to gather structured suggestions for new API endpoints.
- **Template Creation**: Introduces `api_addition.md`, a template that guides contributors in suggesting new API endpoints, ensuring consistency with existing templates.
- **Content Structure**: Includes sections for a detailed API description, URL, and usage examples, facilitating a comprehensive understanding of proposed APIs.
- **Labeling and Assignment**: Automatically assigns the label "api addition" to new issues created with this template, streamlining the categorization process.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/iss …
> Add API addition issue template

- lib/tasks/README.md
- Add `lib/tasks/README.md`
- Describe what is expected in `lib/tasks`
> chore: Add README.md to lib/tasks directory

- .gitignore
- README.md
> Restore README.md

- index.html
- src/App.tsx
> feat: Update page title and header in index.html and App.tsx

- lib/data/opencellid.org/index.yaml
- Close: #39
Adds a new YAML file to describe the OpenCelliD data source in the repository.
- Introduces `lib/data/opencellid.org/index.yaml` with metadata including `data_id`, `license`, `attributions`, `description`, `data_format`, `file_format`, `file_size`, and `url`.
- Specifies the OpenCelliD data source with a `data_id` of `opencellid_full`.
- Sets the license to `CC-BY-SA-4.0` and includes attributions to OpenCelliD and its URL.
- Describes the OpenCelliD data and its uses in the `description` field.
- Defines the data format as `csv` and the file format as `gzipped_csv`.
- Notes the file size as `105MB`.
- Provides a download URL with a placeholder for the API key.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/ …
> Add OpenCelliD data source and processing script

- .vscode/settings.json
- Makefile
- lib/data/ucdp.uu.se/ged231-csv.zip/index.yaml
- lib/tasks/opencellid_full/pmtiles/Makefile
- lib/tasks/ucdp_ged_23_1/pmtiles/Makefile
- Too many changes to explain
- Close: https://github.com/UNopenGIS/foil4g/issues/42
> Add tasks/**/pmtiles/Makefile

- .vscode/settings.json
- lib/data/data.source.coop/smartmaps/rwanda10/index.yaml
> feat: Add Rwanda10 terrain tiles from smartmaps

- lib/tasks/opencellid_full/pmtiles/Makefile
- fix typo on the output file name
- to upload the output file to Source Cooperative nicely. 
- by fixing typo
> Update Makefile to fix typo

- lib/data/data.source.coop/smartmaps/opencellid/index.yaml
> Add OpenCelliD PMTiles converted data for UN Smart Maps

- src/App.tsx
- src/components/OpenStreetMapJpOSMBrightVector/index.tsx
> Add OpenStreetMapJpOSMBrightVector to GitHub Pages

- src/components/OpenStreetMap/OpenStreetMapJpOSMBrightVector/index.tsx
- src/components/OpenStreetMap/OpenStreetMapOrgRaster/index.tsx
- src/components/UNClearMapRaster/index.tsx
> fix style of map

- .vscode/settings.json
- public/stylejson/opencellid.org/style.json
> Tweak style of preview of OpenCellId

- src/components/Combined/OpenCellId/index.stories.ts
- src/components/mapStyleOptions.ts
> feat: Add mapStyleOptions for different map styles

- lib/data/data.source.coop/smartmaps/uppsala-conflict/index.yaml
- src/components/Combined/ArmedConflictWithBaseMap/index.stories.ts
- src/components/Combined/ArmedConflictWithBaseMap/index.tsx
- src/components/Combined/OpenCellIdWithBaseMap/index.stories.ts
- src/components/Combined/OpenCellIdWithBaseMap/index.tsx
- SSIA
- Thanks to @hfu 
- https://github.com/UNopenGIS/7/issues/543
> feat: Add Uppsala Conflict Data Program PMTiles

- lib/data/tile.openstreetmap.jp/overture_pmtiles/index.yaml
> Add Overture Maps PMTiles data

- src/components/Combined/ArmedConflictWithBaseMap/index.tsx
- src/components/Combined/OpenCellIdWithBaseMap/index.tsx
- src/components/Datasets/OpenCellId/index.tsx
- src/components/Datasets/OvertureMaps/index.stories.ts
- src/components/Datasets/OvertureMaps/index.tsx
> feat: Add preview of PMTiles of Overture Maps by OSMFJ

- src/components/Combined/ArmedConflictWithBaseMap/index.tsx
- src/components/Combined/OpenCellIdWithBaseMap/index.tsx
- src/components/Datasets/ArmedConflict/index.stories.ts
- src/components/Datasets/ArmedConflict/index.tsx
- src/components/Datasets/ArmedConflict/source.ts
- src/components/Datasets/OpenCellId/index.tsx
- src/components/Datasets/OpenCellId/source.ts
- src/components/Datasets/OvertureMaps/source.ts
- src/components/PMTilesSourceOptions.ts
- src/types/PMTilesSource.d.ts
> tweak PMTiles source

- .vscode/settings.json
- src/components/Datasets/Rwanda10/index.stories.ts
- src/components/Datasets/Rwanda10/index.tsx
- src/components/Datasets/Rwanda10/source.ts
- src/types/PMTilesSource.d.ts
> Add preview of DEM of Rwanda

- src/components/Combined/OpenCellIdWithDEM1A/index.stories.ts
- src/components/Combined/OpenCellIdWithDEM1A/index.tsx
- src/components/Datasets/OpenCellId/source.ts
> Add combined preview of OpenCellId and DEM1A

- src/components/Combined/OpenCellIdWithDEM1AAndOverture/index.stories.tsx
- src/components/Combined/OpenCellIdWithDEM1AAndOverture/index.tsx
- src/components/Combined/OpenCellIdWithOverture/index.stories.tsx
- src/components/Combined/OpenCellIdWithOverture/index.tsx
- src/components/Datasets/OvertureMaps/source.ts
> feat: Add preview of combined map of OpenCellId and Overture Maps

- src/components/Combined/ArmedConflictWithRwanda10AndOverture/index.stories.ts
- src/components/Combined/ArmedConflictWithRwanda10AndOverture/index.tsx
> feat: Add ArmedConflictWithRwanda10AndOverture component

- src/components/Combined/OpenCellIdWithRwanda10AndOverture/index.stories.tsx
- src/components/Combined/OpenCellIdWithRwanda10AndOverture/index.tsx
- src/components/Combined/RwandaMap/index.stories.tsx
- src/components/Combined/RwandaMap/index.tsx
- src/components/Datasets/ArmedConflict/source.ts
> Add more preview: RwandaMap

- .vscode/settings.json
- src/components/Combined/VientianeLanduseMap/index.stories.ts
- src/components/Combined/VientianeLanduseMap/index.tsx
- src/components/Datasets/VientianeLanduse/source.ts
> feat: Add preview of vientiane landuse (maybe work on github.io)

- src/components/Datasets/VientianeLanduse/source.ts
- Fix mistake of `src/components/Datasets/VientianeLanduse/source.ts`
> feat: Update VientianeLandusePMTilesSource URL to use tiles array

- src/components/Combined/VientianeLanduseWithOpenCellIdAndOverture/index.stories.ts
- src/components/Combined/VientianeLanduseWithOpenCellIdAndOverture/index.tsx
- src/components/Combined/VientianeLanduseWithOverture/index.stories.ts
- src/components/Combined/VientianeLanduseWithOverture/index.tsx
> feat: Update VientianeLanduseWithOpenCellIdAndOverture component

- lib/data/data.source.coop/smartmaps/gel/index.yaml
- Close: #94
Adds the Smart Maps Global Elevation Tiles data source to the repository.
- Creates a new `index.yaml` file under `lib/data/data.source.coop/smartmaps/gel/` with metadata for the Smart Maps Global Elevation Tiles data source.
- Includes comprehensive metadata such as data ID, license, attributions to NASADEM and Global Map, a detailed description of the dataset, data format, file format, URL, and zoom levels as specified in the issue description.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/UNopenGIS/foil4g/issues/94?shareId=44e599da-02dc-4acc-81db-deee082e3494).
> Add Smart Maps Global Elevation Tiles data source

- src/components/Datasets/GEL/index.stories.ts
- src/components/Datasets/GEL/index.tsx
- src/components/Datasets/GEL/source.ts
- Close: #96
This pull request introduces the `GELMap` component to the UNopenGIS/foil4g project, fulfilling the requirement to implement this component within `src/component/Datasets/GEL/index.tsx` using the source data provided in `lib/data/data.source.coop/smartmaps/gel/index.yaml`.
- **Source Configuration**: Adds a new file `src/components/Datasets/GEL/source.ts` defining the `GELPMTilesSource` object. This configuration includes the source ID, URL, type, attribution, max and min zoom levels, terrain source, and a hillshade layer with specific paint properties.
- **Component Implementation**: Implements the `GELMap` component in `src/components/Datasets/GEL/index.tsx`. This component utilizes `useEffect` to integrate the PMTiles protocol with `maplibregl`, and renders a map using the …
> Implement Smart Maps GEL Map component

- src/components/Datasets/GEL/index.tsx
- src/components/Datasets/GEL/source.ts
> Smart Maps GELを完全に理解した

- src/components/Datasets/VientianeLanduse/source.ts
> Update VientianeLandusePMTilesSource URL to use new data source

- src/components/Datasets/VientianeLanduse/index.stories.ts
- src/components/Datasets/VientianeLanduse/index.tsx
> feat: Add VientianeLanduseMap component

- .storybook/manager.ts
> chore: Update navSize in .storybook/manager.ts to 300

- src/App.tsx
- src/components/Combined/ArmedConflictWithBaseMap/index.tsx
- src/components/Combined/ArmedConflictWithOverture/index.tsx
- src/components/Combined/ArmedConflictWithRwanda10AndOverture/index.tsx
- src/components/Combined/OpenCellIdWithBaseMap/index.tsx
- src/components/Combined/OpenCellIdWithDEM1A/index.tsx
- src/components/Combined/OpenCellIdWithDEM1AAndOverture/index.tsx
- src/components/Combined/OpenCellIdWithOverture/index.tsx
- src/components/Combined/OpenCellIdWithRwanda10AndOverture/index.tsx
- src/components/Combined/RwandaMap/index.tsx
- src/components/Combined/VientianeLanduseMap/index.tsx
- src/components/Combined/VientianeLanduseWithOpenCellIdAndOverture/index.tsx
- src/components/Combined/VientianeLanduseWithOverture/index.tsx
- src/components/Datasets/ArmedConflict/index.tsx
- src/components/Datasets/DEM1A/index.tsx
- src/components/Datasets/GEL/index.tsx
- src/components/Datasets/OpenCellId/index.tsx
- src/components/Datasets/OvertureMaps/index.tsx
- src/components/Datasets/Rwanda10/index.tsx
- src/components/Datasets/VientianeLanduse/index.tsx
- src/components/Maps/OpenStreetMap/OpenStreetMapFrHotRaster/index.tsx
- src/components/Maps/OpenStreetMap/OpenStreetMapJpOSMBrightVector/index.tsx
- src/components/Maps/OpenStreetMap/OpenStreetMapOrgRaster/index.tsx
- src/components/Maps/SatelliteImagery/ArcGISWorldImagery/index.tsx
- src/components/Maps/SatelliteImagery/GSISeamlessPhoto/index.tsx
- src/components/Maps/UNClearMapRaster/index.tsx
- Storybookで表示コンポーネントを切り替えてもinitialViewStateが反映されない問題を修正
> Replace `hash={true}` -> `hash={false}`

- src/components/Datasets/GoogleOpenBuildings/index.stories.ts
- src/components/Datasets/GoogleOpenBuildings/index.tsx
- src/components/Datasets/GoogleOpenBuildings/source.ts
- Add Google Open Buildings dataset
- https://github.com/UNopenGIS/7/issues/559
> Add Google Open Buildings dataset

- src/components/Datasets/Rwanda10/source.ts
- src/examples/Stories/RwandaMap/index.stories.tsx
- src/examples/Stories/RwandaMap/index.tsx
> chore: refine example of rwanda

- public/stylejson/geoservices.un.org/clearmap_dark/style.json
- src/components/Maps/UNClearMapDarkRaster/index.stories.ts
- src/components/Maps/UNClearMapDarkRaster/index.tsx
> Add un clear map dark style

- public/stylejson/geoservices.un.org/clearmap_dark/style.json
> Update style.json to use "un_clearmap_dark" as the data source

- .vscode/settings.json
- src/components/Datasets/KonturPopulation/index.stories.ts
- src/components/Datasets/KonturPopulation/index.tsx
- src/components/Datasets/KonturPopulation/source.ts
> Add KonturPopulationMap

- .vscode/settings.json
- src/lib/react-google-maps/index.stories.ts
- src/lib/react-google-maps/index.tsx
- src/lib/react-leaflet/index.stories.ts
- src/lib/react-leaflet/index.tsx
- src/lib/react-map-gl/index.stories.ts
- src/lib/react-map-gl/index.tsx
> Add react-map-gl to lib
